### ISSUE TITLE
[PE-D][Tester C] Cabin service directors can be linked to a flight using the sfa command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#206]
Command :
![image.png](https://raw.githubusercontent.com/Saha9616/ped/main/files/2ab4bdd6-1a63-4f64-af1e-2a1caacc0c3f.png)

csd john linked as an sfa :

![image.png](https://raw.githubusercontent.com/Saha9616/ped/main/files/baab0951-aa23-45de-992a-d4a6ab282b09.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Saha9616/ped#7

**Comment by wxxedu** [comment]
@AY2223S2-CS2103T-W11-1/developers This is related to the link problem that we faced earlier. Since we didn't fix this in the last round, we probably wouldn't fix this in this round either. We should probably specify in the documentation that there is no validation because for a small airline, some of the positions can be used interchangeably.

**Comment by jishnu28** [comment]
to be fixed by renaming crew ranks to titles unrelated to their positions in a flight. This issue is similar to #219
